# Generated by Django 4.1 on 2022-08-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_rename_commment_commentmodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='likesmodel',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
